# Generated by Django 5.1.7 on 2025-03-20 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_fairecategory_newscategory_alter_chat_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faire',
            options={'verbose_name': 'faire', 'verbose_name_plural': 'faires'},
        ),
        migrations.AlterModelOptions(
            name='fairecategory',
            options={'verbose_name': 'faire category', 'verbose_name_plural': 'faire categories'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.AlterModelOptions(
            name='newscategory',
            options={'verbose_name': 'news category', 'verbose_name_plural': 'news categories'},
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='v1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'favorites',
                'verbose_name_plural': 'favorites',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
