services:
  backend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile
    working_dir: /app/backend
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"
    networks:
      - shop_api_network
    env_file:
      - ../../.env
    command: >
      bash -c "
        export PYTHONPATH=/app &&
        poetry install --no-root &&
        poetry run ruff check &&
        poetry run mypy api/ &&
        poetry run python manage.py makemigrations &&
        poetry run python manage.py migrate &&
        poetry run python manage.py test &&
        # poetry run daphne -b 0.0.0.0 -p 8000 backend.config.asgi:application
        poetry run python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      - redis
      - database

  database:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - ../../.env
    networks:
      - shop_api_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - shop_api_network

volumes:
  postgres_data:
    driver: local

networks:
  shop_api_network:
    driver: bridge

name: django_online_shop_api
