export const CATEGORIES = [
    { id: 1, title: 'Куртка', types: 'Adidas', image: '/images/category.jpg', count: '20' },
    { id: 2, title: 'Футболка', types: 'Nike', image: '/images/category.jpg', count: '20' },
    { id: 3, title: 'Джинсы', types: 'Levi\'s', image: '/images/category.jpg', count: '20' },
    { id: 4, title: 'Кроссовки', types: 'Puma', image: '/images/category.jpg', count: '20' },
    { id: 5, title: 'Худи', types: 'Champion', image: '/images/category.jpg', count: '20' },
    { id: 6, title: 'Рубашка', types: 'Tommy Hilfiger', image: '/images/category.jpg', count: '20' },
    { id: 7, title: 'Костюм', types: 'Armani', image: '/images/category.jpg' , count: '20'},
    { id: 8, title: 'Брюки', types: 'Zara', image: '/images/category.jpg' , count: '20'},
    { id: 9, title: 'Юбка', types: 'H&M', image: '/images/category.jpg', count: '20' },
    { id: 10, title: 'Шорты', types: 'Reebok', image: '/images/category.jpg', count: '20' },
    { id: 11, title: 'Толстовка', types: 'Under Armour', image: '/images/category.jpg', count: '20' },
    { id: 12, title: 'Пальто', types: 'Burberry', image: '/images/category.jpg' , count: '20'},
    { id: 13, title: 'Кепка', types: 'New Era', image: '/images/category.jpg', count: '20' },
    { id: 14, title: 'Спортивный костюм', types: 'Fila', image: '/images/category.jpg', count: '20' },
    { id: 15, title: 'Свитер', types: 'Lacoste' , image: '/images/category.jpg', count: '20'},
    { id: 16, title: 'Шарф', types: 'Gucci' , image: '/images/category.jpg', count: '20'},
    { id: 17, title: 'Платье', types: 'Versace', image: '/images/category.jpg', count: '20' },
    { id: 18, title: 'Майка', types: 'Calvin Klein', image: '/images/category.jpg', count: '20'},
    { id: 19, title: 'Ботинки', types: 'Timberland' , image: '/images/category.jpg', count: '20'},
    { id: 20, title: 'Пижама', types: 'Victoria\'s Secret' , image: '/images/category.jpg', count: '20'},
];